source "https://rubygems.org"

ruby "3.3.0"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.0.2"
gem 'actioncable', '~> 8.0.2'

# Use postgresql as the database for Active Record
gem "pg", "~> 1.5.5"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 6.5.0"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use Redis adapter to run Action Cable in production
gem "redis", "~> 5.4"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
gem "bcrypt", "~> 3.1.7"
gem "bugsnag", "~> 6.27"
gem "config", "~> 5.6.0"
gem "figaro", "~> 1.2"
gem "geocoder", "~> 1.8.5"
gem "grape", "~> 2.4"
gem "grape-entity", "~> 1.0.1"
gem "grape-swagger", "~> 2.1.2"
gem "grape-swagger-entity", "~> 0.6.2"
gem "grape-swagger-rails", "~> 0.6.0"
gem "jwt", "~> 2.7.0"
gem "net-imap", "~> 0.5.7"
gem "nokogiri", "~> 1.18.8"
gem "pagy", "~> 9.3.5"
gem "rack", "~> 3.1.14"
gem "rack-session", "~> 2.1.1"
gem "json", "~> 2.6.0"
gem "sprockets-rails", "~> 3.5.2"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", "~> 1.2025.2" , platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", "~> 1.18.6", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
gem "rack-cors", "~> 3.0.0"
gem "openssl", "~> 3.0.0"
gem "web-push", "~> 3.0.1"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: [:mri, :mingw, :mswin, :x64_mingw, :jruby]
  gem "pry"
  gem "pry-nav"
  gem "pry-rails"
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end
